services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: pg_dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"

  pagamento:
    build: .
    container_name: pagamento
    ports:
      - "5001:5001"
    env_file:
      - .env.local
    depends_on:
      - dynamodb
